name: LLVM build

on:
  push:
    branches: main
  pull_request:

jobs:
  llvm:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        version: [21.1.0]
        os: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v4

    - name: Download source for Clang/LLVM ${{ matrix.version }}
      run: |
        curl -L https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-${{ matrix.version }}.tar.gz | tar -xz

    - name: Install build prerequisites
      run: |
        sudo apt-get -y install cmake

    - name: Build xunused for Clang/LLVM ${{ matrix.version }}
      run: |
        cd llvm-project-llvmorg-${{ matrix.version }}
        mkdir build
        cmake -B build -S llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS=clang -DLLVM_EXTERNAL_PROJECTS=xunused -DLLVM_EXTERNAL_XUNUSED_SOURCE_DIR=..
        make -C build xunused

    - name: Run tests
      run: cmake --build build --target check
